################################
# 🦎 KOMODO COMPOSE SETUP 🦎 #
################################

## This compose file will deploy:
##   1. MongoDB
##   2. Komodo Core
##   3. Komodo Periphery

services:
  # MongoDB
  mongo:
    image: mongo
    container_name: komodo-mongo
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    networks:
      - default
    volumes:
      - "/opt/appdata/komodo/mongo/data:/data/db"
      - "/opt/appdata/komodo/mongo/config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    labels:
      komodo.skip: true  # Prevent Komodo from stopping with StopAllContainers

  # Komodo Core
  komodo-core:
    image: ghcr.io/mbecker20/komodo:latest
    container_name: komodo-core
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - default
    ports:
      - 9120:9120  # Web UI
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "/opt/appdata/komodo/core/repo-cache:/repo-cache"
    labels:
      komodo.skip: true  # Prevent Komodo from stopping with StopAllContainers

  # Komodo Periphery
  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:latest
    container_name: komodo-periphery
    restart: unless-stopped
    networks:
      - default
    env_file: .env
    environment:
      KOMODO_CORE_HOST: komodo-core:9120
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Mount external docker socket
      - "/proc:/proc"  # Allow Periphery to see processes outside of container
      - "/opt/appdata/komodo/periphery/ssl:/etc/komodo/ssl"  # SSL certificates
      - "/opt/appdata/komodo/periphery/repos:/etc/komodo/repos"  # Repositories
      - "/opt/appdata/komodo/periphery/stacks:/etc/komodo/stacks"  # Stack files
    depends_on:
      - komodo-core
    labels:
      komodo.skip: true  # Prevent Komodo from stopping with StopAllContainers

networks:
  default: {}
