global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['nix-metrics:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['nix-metrics:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['nix-metrics:8080']

  - job_name: 'tailscale'
    # metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'nix-metrics:5252' # tailscale set --webclient and tailscale metrics
        - 'n8n:5252'
        - 'oi:5252'
        - 'mini:5252'
        - 'mb0:5252'
        - 'dokploy-00:5252'
        - 'dokploy-01:5252'
        - 'dokploy-02:5252'
        - 'dokploy-03:5252'
        - 'dokploy-04:5252'
        - 'dokploy-05:5252'
