global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['nix-metrics:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['nix-metrics:8080']

  - job_name: 'promcontainer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nix-metrics:5252'] # tailscale set --webclient and tailscale metrics
