# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <string> url
    url: ${PROMETHEUS_URL}
    # <bool> mark as default datasource. Default: false
    isDefault: true
    # <bool> allow users to edit datasources from the UI. Default: false
    editable: true
    # <string> unique datasource identifier
    uid: prometheus
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <bool> enable/disable basic auth
    basicAuth: false
    # <bool> enable/disable with credentials headers
    withCredentials: false
    # <bool> mark as a read-only datasource. Default: false
    readOnly: false
    # <map> fields that will be converted to json and stored in jsonData
    jsonData:
      httpMethod: GET
      timeInterval: 15s
