---
  - hosts: nix-llm
    roles:
      - role: ironicbadger.docker-compose-generator
        tags: compose

  - hosts: nix-komodo
    vars:
      docker_compose_hostname: "nix-komodo"
    roles:
      - role: ironicbadger.docker-compose-generator
        tags: compose
