---
  - hosts: nix-llm
    roles:
      - role: ironicbadger.docker-compose-generator
        tags: compose

  - hosts: nix-komodo
    roles:
      - role: ironicbadger.docker-compose-generator
        tags: compose