---
  - hosts: nix-llm
    vars:
      docker_compose_output_path: "/opt/llm"
      docker_compose_generator_output_path: "/opt/llm"
    tasks:
      - name: Ensure /opt/llm directory exists
        file:
          path: "{{ docker_compose_output_path }}"
          state: directory
          mode: '0755'
        tags: [compose, config_files, llm_config]

      - name: Copy openwebui.json file
        copy:
          src: "{{ playbook_dir }}/services/nix-llm/openwebui.json"
          dest: "{{ docker_compose_output_path }}/openwebui.json"
        tags: [compose, config_files, llm_config]
    roles:
      - role: ironicbadger.docker-compose-generator
        tags: compose

  - hosts: nix-metrics
    vars:
      docker_compose_output_path: "/opt/metrics"
      docker_compose_generator_output_path: "/opt/metrics"
      prometheus_user_id: "65534"
      prometheus_group_id: "65534"
      grafana_user_id: "1000"
      grafana_group_id: "1000"
    tasks:
      - name: Ensure /opt/metrics directory exists
        file:
          path: "{{ docker_compose_output_path }}"
          state: directory
          mode: '0755'
        tags: [compose, config_files, metrics_config]

      - name: Copy all files and directories from nix-metrics
        copy:
          src: "{{ playbook_dir }}/services/nix-metrics/"
          dest: "{{ docker_compose_output_path }}/"
          directory_mode: '0755'
        tags: [compose, config_files, metrics_config]
        
      - name: Copy .env.example to .env if .env doesn't exist
        copy:
          src: "{{ playbook_dir }}/services/nix-metrics/.env.example"
          dest: "{{ docker_compose_output_path }}/.env"
          force: no
        tags: [compose, config_files, metrics_config]
        
      - name: Ensure Prometheus data directory exists
        file:
          path: "{{ docker_compose_output_path }}/prometheus/data"
          state: directory
          mode: '0755'
          owner: "{{ prometheus_user_id }}"
          group: "{{ prometheus_group_id }}"
        tags: [compose, config_files, metrics_config]
        
      - name: Ensure Grafana directories exist with correct permissions
        file:
          path: "{{ docker_compose_output_path }}/{{ item }}"
          state: directory
          mode: '0755'
          owner: "{{ grafana_user_id }}"
          group: "{{ grafana_group_id }}"
          recurse: yes
        with_items:
          - grafana/data
          - grafana/dashboards
          - grafana/provisioning/dashboards
          - grafana/provisioning/datasources
        tags: [compose, config_files, metrics_config]
    roles:
      - role: ironicbadger.docker-compose-generator
        tags: compose

  - hosts: nix-komodo
    vars:
      docker_compose_hostname: "nix-komodo"
      docker_compose_output_path: "/opt/komodo"
      docker_compose_generator_output_path: "/opt/komodo"
    tasks:
      - name: Ensure /opt/komodo directory exists
        file:
          path: "{{ docker_compose_output_path }}"
          state: directory
          mode: '0755'
        tags: [compose, config_files, komodo_config]

      - name: Copy .env file
        copy:
          src: "{{ playbook_dir }}/services/nix-komodo/.env"
          dest: "{{ docker_compose_output_path }}/.env"
        tags: [compose, config_files, komodo_config]
    roles:
      - role: ironicbadger.docker-compose-generator
        tags: compose
